### ISSUE TITLE
Smart contracts foundation

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/dmeetup#19]
Lay out the foundation for the platform's smart contracts

**Comment by friedger** [comment]
This is a good starting point: https://github.com/EOSIO/eosio-project-boilerplate-simple/

**Comment by friedger** [comment]
Or even go a step further and move the parts into a services folder like in https://github.com/MonsterEOS/monstereos

**Comment by gaboesquivel** [comment]
solved by https://github.com/eoscostarica/dmeetup/commit/c46411991c45d16db9c2af70b9a38bdbca1646f4.  

Thanks @friedger
