### ISSUE TITLE
Project page

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/dmeetup#21]
We need a landing page for the project. I think we can use github pages to host it, on the standard `gh-pages` branch. 

Related to #5

**Comment by gaboesquivel** [comment]
This is a nice ref https://hirevibes.io, it's another EOS project

**Comment by gaboesquivel** [comment]
Here's another example
https://about.dlive.io/

@murillojorge @laubits

**Comment by friedger** [comment]
What is the landing page about? If it is about explaining the project it it should be part of the front end at https://dmeetup.netlify.com/

If it is about attracting contributors then the README or doc folder on github should be enough.

**Comment by gaboesquivel** [comment]
I agree.
