### ISSUE TITLE
Why EOS and not Steem blockchain.

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/dmeetup#22]
The DMeetup project is very similar to DTube, which is a decentralized version of YouTube. Steem Blockchain already provides some of the features we want on the DApp. As we advanced in our validation and R&D process we need properly communicate why we decide to use one platform or the other, or a combination of the two. 

Related to #4

**Comment by friedger** [comment]
DTube and steem in general makes the meetups compete with the other content created on that platform and compete for the same money.
EOS in contrast allows you to create your own money and voting rules.

**Comment by gaboesquivel** [comment]
Yes, and steem is for content while we focus on events.
