### ISSUE TITLE
Add a github corner to the site

### ISSUE THREAD

**Issue by gaboesquivel** [eoscostarica/dmeetup#40]
What do you think about adding a github corner to staging site ?

http://tholman.com/github-corners/

**Comment by kevin-wolf** [comment]
Uhm, I personally think that corner looks odd on this kind of project, imo the corner is more suitable for open source projects.

What I will suggest is using a footer that says something like `Created with ♥️ by EOS Costa Rica` or something like that.

What do you think?

**Comment by gaboesquivel** [comment]
This an open source project :).. The fact that there an crypto economics system doesn't mean we need to it different, it's totally open source. 

But yeah, I think I got your point. I think it is good to have a link to project, a call to collaborate somewhere.

**Comment by kevin-wolf** [comment]
Yeah actually i've misspelled it. I wanted to say "open source projects like frameworks or libraries".
