### ISSUE TITLE
EOS Dmetup IPFS not working

### ISSUE THREAD

**Issue by Sabrinsulthana** [eoscostarica/dmeetup#67]
Hi friends,
  I found an error while generating the Dmeetup project in IPFS. it shows failed to compile with the Hook.js file. I cant recover this error. Please help me to solve this issue.
Failed to compile.

  TypeError: compilation.templatesPlugin is not a function
  
  - SetVarMainTemplatePlugin.js:17 SetVarMainTemplatePlugin.apply
    [dmeetup]/[webpack]/lib/SetVarMainTemplatePlugin.js:17:15
  
  - Tapable.js:79 Compilation.apply
    [dmeetup]/[react-scripts]/[tapable]/lib/Tapable.js:79:16
  
  - util.js:67 Compilation.deprecated [as apply]
    internal/util.js:67:15
  
  - LibraryTemplatePlugin.js:45 compiler.plugin
    [dmeetup]/[webpack]/lib/LibraryTemplatePlugin.js:45:18
  
  
  - Hook.js:154 SyncHook.lazyCompileHook
    [dmeetup]/[react-scripts]/[tapable]/lib/Hook.js:154:20
  
  - Compiler.js:503 Compiler.newCompilation
    [dmeetup]/[react-scripts]/[webpack]/lib/Compiler.js:503:30
  
  - Compiler.js:540 hooks.beforeCompile.callAsync.err
    [dmeetup]/[react-scripts]/[webpack]/lib/Compiler.js:540:29
  
  
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [dmeetup]/[react-scripts]/[tapable]/lib/Hook.js:154:20

Thanks in advance..

**Comment by friedger** [comment]
What are you running? `yarn build`?

**Comment by gaboesquivel** [comment]
The site is back up https://dmeetup.io/

We are currently using netlify.

Check v0.1 Simplication as well #74.  We might just launch with EOS ( no dmeetup token for now ).

The IPFS part it is for storing files ( images for sure and maybe some json, but that will depend on EOS Storage costs I guess. )
