### ISSUE TITLE
frontend issue

### ISSUE THREAD

**Issue by Sabrinsulthana** [eoscostarica/dmeetup#68]
Hi friends,
 I didnt get the front end also..So please rectify this issue.
Thanks in advance..

**Comment by morenoh149** [comment]
is the issue that https://dmeetup.io won't load?

**Comment by gaboesquivel** [comment]
thanks for the heads up @Sabrinsulthana. we are transferring the domain, will be up again soon. It's also very early, you'll see the layout and initial mocked landing page.

Notes: 
- currently the @eoscostarica/core is focusing efforts on launching https://github.com/eoscostarica/rate.eoscostarica.io. So it's kinda paused right now.
- this is community driven project, feel free propose and collaborate on any area.

We are also on https://eoscostarica.io/discord

**Comment by friedger** [comment]
@Sabrinsulthana you can see the front end at netlify: https://dmeetup.netlify.com/
